### PR TITLE
added powerapp package

### PR DESCRIPTION
**Pull request by msavita-cloud**

### CODE REVIEW

**Review by louis-li — APPROVED** [review]
Thanks, we need this demo.

**Comment by louis-li** [comment]
@aldelar can you take a look at this PR please.

**Comment by msavita-cloud** [comment]
@microsoft-github-policy-service agree

**Comment by ryubidragonfire** [comment]
@msavita-cloud  Please remember to add your details in AUTHORS.md

**Comment by msavita-cloud** [comment]
I have added all the details in authors.md.

**Pull request merged**
